/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    registrants: Registrant;
    'google-tokens': GoogleToken;
    'google-sheets-creds': GoogleSheetsCred;
    syahadah: Syahadah;
    'profile-photo': ProfilePhoto;
    'confirmation-pdf': ConfirmationPdf;
    'registration-settings': RegistrationSetting;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    registrants: RegistrantsSelect<false> | RegistrantsSelect<true>;
    'google-tokens': GoogleTokensSelect<false> | GoogleTokensSelect<true>;
    'google-sheets-creds': GoogleSheetsCredsSelect<false> | GoogleSheetsCredsSelect<true>;
    syahadah: SyahadahSelect<false> | SyahadahSelect<true>;
    'profile-photo': ProfilePhotoSelect<false> | ProfilePhotoSelect<true>;
    'confirmation-pdf': ConfirmationPdfSelect<false> | ConfirmationPdfSelect<true>;
    'registration-settings': RegistrationSettingsSelect<false> | RegistrationSettingsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrants".
 */
export interface Registrant {
  id: string;
  registrant_type: 'SHOFI' | 'TASHFIYAH' | 'ATRIBUT';
  name: string;
  name_arabic: string;
  gender: 'L' | 'P';
  email: string;
  nationality: string;
  passport_number: string;
  phone_number?: string | null;
  whatsapp: string;
  kekeluargaan?:
    | (
        | 'KMB'
        | 'KMJ'
        | 'KPJ'
        | 'KPMJB'
        | 'KMA'
        | 'KSW'
        | 'KEMASS'
        | 'KKS'
        | 'KSMR'
        | 'KMNTB'
        | 'KMKM'
        | 'KMM'
        | 'IKMAL'
        | 'GAMAJATIM'
        | 'HMMSU'
        | 'FOSGAMA'
      )
    | null;
  university: string;
  education_level: 'S1' | 'S2' | 'S3';
  first_enrollment_year: number;
  graduation_year: number;
  faculty: string;
  major: string;
  quran_memorization: number;
  /**
   * Otomatis dihitung dari graduation_year - first_enrollment_year
   */
  study_duration?: number | null;
  continuing_study?: ('YES' | 'NO' | 'UNDECIDED') | null;
  kulliyah?: string | null;
  syubah?: string | null;
  shofi_ready_attend?: boolean | null;
  predicate?:
    | ('MUMTAZ_MMS' | 'MUMTAZ' | 'JAYYID_JIDDAN_MMS' | 'JAYYID_JIDDAN' | 'JAYYID' | 'MAQBUL' | 'RASIB' | 'DHAIF')
    | null;
  cumulative_score?: number | null;
  syahadah_photo?: (string | null) | Syahadah;
  tashfiyah_ready_attend?: boolean | null;
  tashfiyah_ready_submit_proof?: boolean | null;
  tashfiyah_no_graduation_if_failed?: boolean | null;
  tashfiyah_still_get_attributes?: boolean | null;
  atribut_ready_attend?: boolean | null;
  attribute_package?: ('SELENDANG_PIN_MEDALI' | 'PLAKAT' | 'LENGKAP') | null;
  photo: string | ProfilePhoto;
  terms_agreement: boolean;
  /**
   * Otomatis di-generate berdasarkan ID database
   */
  reg_id?: string | null;
  /**
   * Otomatis di-generate setelah perubahan data
   */
  confirmation_pdf?: (string | null) | ConfirmationPdf;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syahadah".
 */
export interface Syahadah {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile-photo".
 */
export interface ProfilePhoto {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "confirmation-pdf".
 */
export interface ConfirmationPdf {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-tokens".
 */
export interface GoogleToken {
  id: string;
  google_user_id: string;
  email: string;
  name: string;
  accessToken: string;
  refreshToken?: string | null;
  expiresAt: string;
  refreshExpiresAt?: string | null;
  rawResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-sheets-creds".
 */
export interface GoogleSheetsCred {
  id: string;
  title: string;
  spreadsheetId: string;
  spreadsheetUrl: string;
  lastRange?: string | null;
  lastUpdatedCells?: number | null;
  rowsSynced?: number | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pengaturan batas maksimal pendaftar
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registration-settings".
 */
export interface RegistrationSetting {
  id: string;
  name: string;
  /**
   * Jumlah maksimal pendaftar yang diperbolehkan
   */
  max_registrants: number;
  /**
   * Deskripsi pengaturan (opsional)
   */
  description?: string | null;
  /**
   * Apakah pengaturan ini sedang aktif?
   */
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'registrants';
        value: string | Registrant;
      } | null)
    | ({
        relationTo: 'google-tokens';
        value: string | GoogleToken;
      } | null)
    | ({
        relationTo: 'google-sheets-creds';
        value: string | GoogleSheetsCred;
      } | null)
    | ({
        relationTo: 'syahadah';
        value: string | Syahadah;
      } | null)
    | ({
        relationTo: 'profile-photo';
        value: string | ProfilePhoto;
      } | null)
    | ({
        relationTo: 'confirmation-pdf';
        value: string | ConfirmationPdf;
      } | null)
    | ({
        relationTo: 'registration-settings';
        value: string | RegistrationSetting;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrants_select".
 */
export interface RegistrantsSelect<T extends boolean = true> {
  registrant_type?: T;
  name?: T;
  name_arabic?: T;
  gender?: T;
  email?: T;
  nationality?: T;
  passport_number?: T;
  phone_number?: T;
  whatsapp?: T;
  kekeluargaan?: T;
  university?: T;
  education_level?: T;
  first_enrollment_year?: T;
  graduation_year?: T;
  faculty?: T;
  major?: T;
  quran_memorization?: T;
  study_duration?: T;
  continuing_study?: T;
  kulliyah?: T;
  syubah?: T;
  shofi_ready_attend?: T;
  predicate?: T;
  cumulative_score?: T;
  syahadah_photo?: T;
  tashfiyah_ready_attend?: T;
  tashfiyah_ready_submit_proof?: T;
  tashfiyah_no_graduation_if_failed?: T;
  tashfiyah_still_get_attributes?: T;
  atribut_ready_attend?: T;
  attribute_package?: T;
  photo?: T;
  terms_agreement?: T;
  reg_id?: T;
  confirmation_pdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-tokens_select".
 */
export interface GoogleTokensSelect<T extends boolean = true> {
  google_user_id?: T;
  email?: T;
  name?: T;
  accessToken?: T;
  refreshToken?: T;
  expiresAt?: T;
  refreshExpiresAt?: T;
  rawResponse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-sheets-creds_select".
 */
export interface GoogleSheetsCredsSelect<T extends boolean = true> {
  title?: T;
  spreadsheetId?: T;
  spreadsheetUrl?: T;
  lastRange?: T;
  lastUpdatedCells?: T;
  rowsSynced?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syahadah_select".
 */
export interface SyahadahSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile-photo_select".
 */
export interface ProfilePhotoSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "confirmation-pdf_select".
 */
export interface ConfirmationPdfSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registration-settings_select".
 */
export interface RegistrationSettingsSelect<T extends boolean = true> {
  name?: T;
  max_registrants?: T;
  description?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}